<?php

declare (strict_types=1);
namespace Psr\Cache;

/**
 * CacheItemInterface defines an interface for interacting with objects inside a cache.
 *
 * Each Item object MUST be associated with a specific key, which can be set
 * according to the implementing system and is typically passed by the
 * Cache\CacheItemPoolInterface object.
 *
 * The Cache\CacheItemInterface object encapsulates the storage and retrieval of
 * cache items. Each Cache\CacheItemInterface is generated by a
 * Cache\CacheItemPoolInterface object, which is responsible for any required
 * setup as well as associating the object with a unique Key.
 * Cache\CacheItemInterface objects MUST be able to store and retrieve any type
 * of PHP value defined in the Data section of the specification.
 *
 * Calling Libraries MUST NOT instantiate Item objects themselves. They may only
 * be requested from a Pool object via the getItem() method.  Calling Libraries
 * SHOULD NOT assume that an Item created by one Implementing Library is
 * compatible with a Pool from another Implementing Library.
 */
interface Cache_Item_Interface
{
    /**
     * Returns the key for the current cache item.
     *
     * The key is loaded by the Implementing Library, but should be available to
     * the higher level callers when needed. Keys are unique within a single pool
     * and are used to address items for get, set, and delete operations.
     *
     * @return string The unique key string identifying this cache item within
     *   its pool. The key is set at item creation time and never changes.
     *
     * @since 1.0
     */
    public function get_key(): string;
    /**
     * Retrieves the value of the item from the cache associated with this object's key.
     *
     * The value returned must be identical to the value originally stored by set().
     *
     * If isHit() returns false, this method MUST return null. Note that null
     * is a legitimate cached value, so the isHit() method SHOULD be used to
     * differentiate between "null value was found" and "no value was found."
     *
     * @return mixed The deserialized cached value, or null on a cache miss.
     *   Always call is_hit() before trusting this value; a null return does
     *   not distinguish a stored null from a missing entry.
     *
     * @see self::is_hit() Use this to determine whether null means "miss" or "stored null".
     * @since 1.0
     */
    public function get(): mixed;
    /**
     * Confirms if the cache item lookup resulted in a cache hit.
     *
     * Note: This method MUST NOT have a race condition between calling isHit()
     * and calling get(). Because a single item object represents both the key
     * and the result, the hit/miss state is frozen at item-fetch time and will
     * not change for the lifetime of the object.
     *
     * @return bool True if the pool contained a valid, non-expired entry for
     *   this item's key at the time it was retrieved. False on a cache miss,
     *   expiry, or any retrieval error.
     *
     * @since 1.0
     */
    public function is_hit(): bool;
    /**
     * Sets the value represented by this cache item.
     *
     * The $value argument may be any item that can be serialized by PHP,
     * although the method of serialization is left up to the Implementing
     * Library. The value is not persisted until save() or save_deferred() is
     * called on the owning pool.
     *
     * @param mixed $value The serializable value to be stored. Resources and
     *   closures are generally not serializable; the implementing library will
     *   throw or silently fail for non-serializable types.
     *
     * @return static The same item instance, allowing method chaining such as
     *   $item->set($value)->expires_after(3600).
     *
     * @since 1.0
     */
    public function set(mixed $value): static;
    /**
     * Sets the absolute expiration time for this cache item.
     *
     * Use this when you know the exact moment the item should expire (e.g.,
     * a session token valid until midnight, or an OAuth token with a known
     * expiry timestamp). For relative expiry, prefer expires_after().
     *
     * @param \DateTimeInterface|null $expiration The point in time after which
     *   the item MUST be considered expired and removed from the pool. Pass null
     *   to use the pool's default TTL, or store indefinitely if no default is set.
     *
     * @return static The same item instance for method chaining.
     *
     * @see self::expires_after() For TTL-based relative expiry.
     * @since 1.0
     */
    public function expires_at(?\DateTimeInterface $expiration): static;
    /**
     * Sets the relative expiration time for this cache item.
     *
     * Use this when you want the item to live for a duration from now rather
     * than until a specific timestamp. An integer value is treated as seconds;
     * passing 3600 means the item expires one hour from the time save() is called.
     *
     * @param int|\DateInterval|null $time The TTL duration. An integer is
     *   interpreted as seconds from the present. A DateInterval allows richer
     *   expressions such as "P1D" for one day. Pass null to use the pool's
     *   default TTL, or store indefinitely if no default is configured.
     *
     * @return static The same item instance for method chaining.
     *
     * @see self::expires_at() For absolute-timestamp expiry.
     * @since 1.0
     */
    public function expires_after(int|\DateInterval|null $time): static;
}